spec:
  name: ourlove-api
  region: sgp
  services:
    - name: api
      github:
        branch: main
        deploy_on_push: true
      dockerfile_path: Dockerfile
      http_port: 8080
      instance_count: 1
      instance_size_slug: basic-xxs
      routes:
        - path: /
      envs:
        - key: SPRING_PROFILES_ACTIVE
          value: "prod"
        - key: DATABASE_URL
          value: "${db-postgresql.DATABASE_URL}"
        - key: CLOUDINARY_CLOUD_NAME
          type: SECRET
        - key: CLOUDINARY_API_KEY
          type: SECRET
        - key: CLOUDINARY_API_SECRET
          type: SECRET
